spring.application.name=spark

spring.jwt.secret_key=${SPRING_JWT_SECRET_KEY}
spring.cors.allowed-origins=${SPRING_CORS_ALLOWED_ORIGINS}

#Disable Hibernate because Flyway will manage schema
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration