spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}

spring.data.redis.username=${REDISUSER}
spring.data.redis.password=${REDISPASSWORD}